---

name: Checks 

on: [push]

jobs:
    test-and-linting:
        runs-on: ubuntu-20.04
        steps:
            - name: Login to Dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Check
              uses: actions/checkout@v4
            - name: Tests
              run: docker compose run --rm app sh -c "python mange.py test"
            - name: Linting
              run: docker compose run --rm app sh -c "flake8"